export const specialties = [
  { value: "None", label: "None" },
  { value: "AllergyAndImmunology", label: "Allergy and Immunology" },
  { value: "Anesthesiology", label: "Anesthesiology" },
  { value: "Cardiology", label: "Cardiology" },
  { value: "Dermatology", label: "Dermatology" },
  { value: "EmergencyMedicine", label: "Emergency Medicine" },
  { value: "Endocrinology", label: "Endocrinology" },
  { value: "FamilyMedicine", label: "Family Medicine" },
  { value: "Gastroenterology", label: "Gastroenterology" },
  { value: "GeneralSurgery", label: "General Surgery" },
  { value: "Geriatrics", label: "Geriatrics" },
  { value: "Hematology", label: "Hematology" },
  { value: "InfectiousDisease", label: "Infectious Disease" },
  { value: "InternalMedicine", label: "Internal Medicine" },
  { value: "Nephrology", label: "Nephrology" },
  { value: "Neurology", label: "Neurology" },
  { value: "Neurosurgery", label: "Neurosurgery" },
  { value: "ObstetricsAndGynecology", label: "Obstetrics and Gynecology" },
  { value: "Oncology", label: "Oncology" },
  { value: "Ophthalmology", label: "Ophthalmology" },
  { value: "Orthopedics", label: "Orthopedics" },
  { value: "Otolaryngology", label: "Otolaryngology" },
  { value: "Pathology", label: "Pathology" },
  { value: "Pediatrics", label: "Pediatrics" },
  {
    value: "PhysicalMedicineAndRehabilitation",
    label: "Physical Medicine and Rehabilitation",
  },
  { value: "PlasticSurgery", label: "Plastic Surgery" },
  { value: "Psychiatry", label: "Psychiatry" },
  { value: "Pulmonology", label: "Pulmonology" },
  { value: "Radiology", label: "Radiology" },
  { value: "Rheumatology", label: "Rheumatology" },
  { value: "Urology", label: "Urology" },
  { value: "VascularSurgery", label: "Vascular Surgery" },
];

export const mangerMenuPages = [
  "Users",
  "Appointments",
  "Medical histories",
  "Visits",
];
export const settings = ["Profile", "Account", "Dashboard", "Logout"];
