export enum Specialty {
  None = 'None',
    AllergyAndImmunology = 'Allergy and Immunology',
    Anesthesiology = 'Anesthesiology',
    Cardiology = 'Cardiology',
    Dermatology = 'Dermatology',
    EmergencyMedicine = 'Emergency Medicine',
    Endocrinology = 'Endocrinology',
    FamilyMedicine = 'Family Medicine',
    Gastroenterology = 'Gastroenterology',
    GeneralSurgery = 'General Surgery',
    Geriatrics = 'Geriatrics',
    Hematology = 'Hematology',
    InfectiousDisease = 'Infectious Disease',
    InternalMedicine = 'Internal Medicine',
    Nephrology = 'Nephrology',
    Neurology = 'Neurology',
    Neurosurgery = 'Neurosurgery',
    ObstetricsAndGynecology = 'Obstetrics and Gynecology',
    Oncology = 'Oncology',
    Ophthalmology = 'Ophthalmology',
    Orthopedics = 'Orthopedics',
    Otolaryngology = 'Otolaryngology',
    Pathology = 'Pathology',
    Pediatrics = 'Pediatrics',
    PhysicalMedicineAndRehabilitation = 'Physical Medicine and Rehabilitation',
    PlasticSurgery = 'Plastic Surgery',
    Psychiatry = 'Psychiatry',
    Pulmonology = 'Pulmonology',
    Radiology = 'Radiology',
    Rheumatology = 'Rheumatology',
    Urology = 'Urology',
    VascularSurgery = 'Vascular Surgery',
  }
  